spring.application.name=seguridadcalidad
server.port=8080
server.servlet.context-path=/recetas
server.error.include-message=never
spring.thymeleaf.cache=false
backend.url=${BACKEND_URL:http://localhost:8081}
