services:
  mysql-isy2202:
    image: mysql/mysql-server:8.0
    container_name: mysql-isy2202
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./sql/01_schema_and_data.sql:/docker-entrypoint-initdb.d/01_schema_and_data.sql:ro

  backend:
    build: ./backend
    container_name: backend-isy2202
    ports:
      - "8081:8080"
    depends_on:
      - mysql-isy2202
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-isy2202:3306/mydatabase?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: password
      APP_JWT_SECRET: SeguridadCalidadJWTSecretKey2026SeguridadCalidadJWT!

  frontend:
    build: ./frontend
    container_name: frontend-isy2202
    ports:
      - "8080:8080"
    depends_on:
      - backend
